<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["name" => "Afghan Afghani", "symbol" => "؋"],
            ["name" => "Albanian Lek", "symbol" => "Lek"],
            ["name" => "Algerian Dinar", "symbol" => "دج"],
            ["name" => "Angolan Kwanza", "symbol" => "Kz"],
            ["name" => "Argentine Peso", "symbol" => "$"],
            ["name" => "Armenian Dram", "symbol" => "֏"],
            ["name" => "Aruban Florin", "symbol" => "ƒ"],
            ["name" => "Australian Dollar", "symbol" => "$"],
            ["name" => "Azerbaijani Manat", "symbol" => "m"],
            ["name" => "Bahamian Dollar", "symbol" => "B$"],
            ["name" => "Bahraini Dinar", "symbol" => ".د.ب"],
            ["name" => "Bangladeshi Taka", "symbol" => "৳"],
            ["name" => "Barbadian Dollar", "symbol" => "Bds$"],
            ["name" => "Belarusian Ruble", "symbol" => "Br"],
            ["name" => "Belgian Franc", "symbol" => "fr"],
            ["name" => "Belize Dollar", "symbol" => "$"],
            ["name" => "Bermudan Dollar", "symbol" => "$"],
            ["name" => "Bhutanese Ngultrum", "symbol" => "Nu."],
            ["name" => "Bitcoin", "symbol" => "฿"],
            ["name" => "Bolivian Boliviano", "symbol" => "Bs."],
            ["name" => "Bosnia", "symbol" => "KM"],
            ["name" => "Botswanan Pula", "symbol" => "P"],
            ["name" => "Brazilian Real", "symbol" => "R$"],
            ["name" => "British Pound Sterling", "symbol" => "£"],
            ["name" => "Brunei Dollar", "symbol" => "B$"],
            ["name" => "Bulgarian Lev", "symbol" => "Лв."],
            ["name" => "Burundian Franc", "symbol" => "FBu"],
            ["name" => "Cambodian Riel", "symbol" => "KHR"],
            ["name" => "Canadian Dollar", "symbol" => "$"],
            ["name" => "Cape Verdean Escudo", "symbol" => "$"],
            ["name" => "Cayman Islands Dollar", "symbol" => "$"],
            ["name" => "CFA Franc BCEAO", "symbol" => "CFA"],
            ["name" => "CFA Franc BEAC", "symbol" => "FCFA"],
            ["name" => "CFP Franc", "symbol" => "₣"],
            ["name" => "Chilean Peso", "symbol" => "$"],
            ["name" => "Chinese Yuan", "symbol" => "¥"],
            ["name" => "Colombian Peso", "symbol" => "$"],
            ["name" => "Comorian Franc", "symbol" => "CF"],
            ["name" => "Congolese Franc", "symbol" => "FC"],
            ["name" => "Costa Rican ColÃ³n", "symbol" => "₡"],
            ["name" => "Croatian Kuna", "symbol" => "kn"],
            ["name" => "Cuban Convertible Peso", "symbol" => "$, CUC"],
            ["name" => "Czech Republic Koruna", "symbol" => "Kč"],
            ["name" => "Danish Krone", "symbol" => "Kr."],
            ["name" => "Djiboutian Franc", "symbol" => "Fdj"],
            ["name" => "Dominican Peso", "symbol" => "$"],
            ["name" => "East Caribbean Dollar", "symbol" => "$"],
            ["name" => "Egyptian Pound", "symbol" => "ج.م"],
            ["name" => "Eritrean Nakfa", "symbol" => "Nfk"],
            ["name" => "Estonian Kroon", "symbol" => "kr"],
            ["name" => "Ethiopian Birr", "symbol" => "Nkf"],
            ["name" => "Euro", "symbol" => "€"],
            ["name" => "Falkland Islands Pound", "symbol" => "£"],
            ["name" => "Fijian Dollar", "symbol" => "FJ$"],
            ["name" => "Gambian Dalasi", "symbol" => "D"],
            ["name" => "Georgian Lari", "symbol" => "ლ"],
            ["name" => "German Mark", "symbol" => "DM"],
            ["name" => "Ghanaian Cedi", "symbol" => "GH₵"],
            ["name" => "Gibraltar Pound", "symbol" => "£"],
            ["name" => "Greek Drachma", "symbol" => "₯, Δρχ, Δρ"],
            ["name" => "Guatemalan Quetzal", "symbol" => "Q"],
            ["name" => "Guinean Franc", "symbol" => "FG"],
            ["name" => "Guyanaese Dollar", "symbol" => "$"],
            ["name" => "Haitian Gourde", "symbol" => "G"],
            ["name" => "Honduran Lempira", "symbol" => "L"],
            ["name" => "Hong Kong Dollar", "symbol" => "$"],
            ["name" => "Hungarian Forint", "symbol" => "Ft"],
            ["name" => "Icelandic KrÃ³na", "symbol" => "kr"],
            ["name" => "Indian Rupee", "symbol" => "₹"],
            ["name" => "Indonesian Rupiah", "symbol" => "Rp"],
            ["name" => "Iranian Rial", "symbol" => "﷼"],
            ["name" => "Iraqi Dinar", "symbol" => "د.ع"],
            ["name" => "Israeli New Sheqel", "symbol" => "₪"],
            ["name" => "Italian Lira", "symbol" => "L,£"],
            ["name" => "Jamaican Dollar", "symbol" => "J$"],
            ["name" => "Japanese Yen", "symbol" => "¥"],
            ["name" => "Jordanian Dinar", "symbol" => "ا.د"],
            ["name" => "Kazakhstani Tenge", "symbol" => "лв"],
            ["name" => "Kenyan Shilling", "symbol" => "KSh"],
            ["name" => "Kuwaiti Dinar", "symbol" => "ك.د"],
            ["name" => "Kyrgystani Som", "symbol" => "лв"],
            ["name" => "Laotian Kip", "symbol" => "₭"],
            ["name" => "Latvian Lats", "symbol" => "Ls"],
            ["name" => "Lebanese Pound", "symbol" => "£"],
            ["name" => "Lesotho Loti", "symbol" => "L"],
            ["name" => "Liberian Dollar", "symbol" => "$"],
            ["name" => "Libyan Dinar", "symbol" => "د.ل"],
            ["name" => "Lithuanian Litas", "symbol" => "Lt"],
            ["name" => "Macanese Pataca", "symbol" => "$"],
            ["name" => "Macedonian Denar", "symbol" => "ден"],
            ["name" => "Malagasy Ariary", "symbol" => "Ar"],
            ["name" => "Malawian Kwacha", "symbol" => "MK"],
            ["name" => "Malaysian Ringgit", "symbol" => "RM"],
            ["name" => "Maldivian Rufiyaa", "symbol" => "Rf"],
            ["name" => "Mauritanian Ouguiya", "symbol" => "MRU"],
            ["name" => "Mauritian Rupee", "symbol" => "₨"],
            ["name" => "Mexican Peso", "symbol" => "$"],
            ["name" => "Moldovan Leu", "symbol" => "L"],
            ["name" => "Mongolian Tugrik", "symbol" => "₮"],
            ["name" => "Moroccan Dirham", "symbol" => "MAD"],
            ["name" => "Mozambican Metical", "symbol" => "MT"],
            ["name" => "Myanmar Kyat", "symbol" => "K"],
            ["name" => "Namibian Dollar", "symbol" => "$"],
            ["name" => "Nepalese Rupee", "symbol" => "₨"],
            ["name" => "Netherlands Antillean Guilder", "symbol" => "ƒ"],
            ["name" => "New Taiwan Dollar", "symbol" => "$"],
            ["name" => "New Zealand Dollar", "symbol" => "$"],
            ["name" => "Nicaraguan CÃ³rdoba", "symbol" => "C$"],
            ["name" => "Nigerian Naira", "symbol" => "₦"],
            ["name" => "North Korean Won", "symbol" => "₩"],
            ["name" => "Norwegian Krone", "symbol" => "kr"],
            ["name" => "Omani Rial", "symbol" => ".ع.ر"],
            ["name" => "Pakistani Rupee", "symbol" => "₨"],
            ["name" => "Panamanian Balboa", "symbol" => "B/."],
            ["name" => "Papua New Guinean Kina", "symbol" => "K"],
            ["name" => "Paraguayan Guarani", "symbol" => "₲"],
            ["name" => "Peruvian Nuevo Sol", "symbol" => "S/."],
            ["name" => "Philippine Peso", "symbol" => "₱"],
            ["name" => "Polish Zloty", "symbol" => "zł"],
            ["name" => "Qatari Rial", "symbol" => "ق.ر"],
            ["name" => "Romanian Leu", "symbol" => "lei"],
            ["name" => "Russian Ruble", "symbol" => "₽"],
            ["name" => "Rwandan Franc", "symbol" => "FRw"],
            ["name" => "Salvadoran ColÃ³n", "symbol" => "₡"],
            ["name" => "Samoan Tala", "symbol" => "SAT"],
            ["name" => "Saudi Riyal", "symbol" => "﷼"],
            ["name" => "Serbian Dinar", "symbol" => "din"],
            ["name" => "Seychellois Rupee", "symbol" => "SRe"],
            ["name" => "Sierra Leonean Leone", "symbol" => "Le"],
            ["name" => "Singapore Dollar", "symbol" => "$"],
            ["name" => "Slovak Koruna", "symbol" => "Sk"],
            ["name" => "Solomon Islands Dollar", "symbol" => "Si$"],
            ["name" => "Somali Shilling", "symbol" => "Sh.so."],
            ["name" => "South African Rand", "symbol" => "R"],
            ["name" => "South Korean Won", "symbol" => "₩"],
            ["name" => "Special Drawing Rights", "symbol" => "SDR"],
            ["name" => "Sri Lankan Rupee", "symbol" => "Rs"],
            ["name" => "St. Helena Pound", "symbol" => "£"],
            ["name" => "Sudanese Pound", "symbol" => ".س.ج"],
            ["name" => "Surinamese Dollar", "symbol" => "$"],
            ["name" => "Swazi Lilangeni", "symbol" => "E"],
            ["name" => "Swedish Krona", "symbol" => "kr"],
            ["name" => "Swiss Franc", "symbol" => "CHf"],
            ["name" => "Syrian Pound", "symbol" => "LS"],
            ["name" => "São Tomé and Príncipe Dobra", "symbol" => "Db"],
            ["name" => "Tajikistani Somoni", "symbol" => "SM"],
            ["name" => "Tanzanian Shilling", "symbol" => "TSh"],
            ["name" => "Thai Baht", "symbol" => "฿"],
            ["name" => "Tongan pa'anga", "symbol" => "$"],
            ["name" => "Trinidad & Tobago Dollar", "symbol" => "$"],
            ["name" => "Tunisian Dinar", "symbol" => "ت.د"],
            ["name" => "Turkish Lira", "symbol" => "₺"],
            ["name" => "Turkmenistani Manat", "symbol" => "T"],
            ["name" => "Ugandan Shilling", "symbol" => "USh"],
            ["name" => "Ukrainian Hryvnia", "symbol" => "₴"],
            ["name" => "United Arab Emirates Dirham", "symbol" => "إ.د"],
            ["name" => "Uruguayan Peso", "symbol" => "$"],
            ["name" => "US Dollar", "symbol" => "$"],
            ["name" => "Uzbekistan Som", "symbol" => "лв"],
            ["name" => "Vanuatu Vatu", "symbol" => "VT"],
            ["name" => "Venezuelan BolÃvar", "symbol" => "Bs"],
            ["name" => "Vietnamese Dong", "symbol" => "₫"],
            ["name" => "Yemeni Rial", "symbol" => "﷼"],
            ["name" => "Zambian Kwacha", "symbol" => "ZK"],
        ];
        Currency::insert($data);
    }
}
